[phases.setup]
nixPkgs = [
  "python312",
  "python312Packages.pip",
  "nodejs_20",
  "stdenv.cc.cc.lib"
]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements-production.txt",
  "npm install",
  "cd order-delight-main && npm install"
]

[phases.build]
cmds = [
  "cd order-delight-main && npm run build"
]

[start]
cmd = "source /opt/venv/bin/activate && bash start.sh"