"""initial

Revision ID: 38c9a37ad0cf
Revises: 
Create Date: 2026-05-14 11:57:20.077103
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c9a37ad0cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

