"""Add redeem_loyalty_points to orders

Revision ID: 48e2c03c6270
Revises: 9b7fe32a4230
Create Date: 2026-05-17 23:31:32.301278
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e2c03c6270'
down_revision = '9b7fe32a4230'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

