"""Add notifications table

Revision ID: 6201befbc815
Revises: 38c9a37ad0cf
Create Date: 2026-05-17 19:31:34.502209
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6201befbc815'
down_revision = '38c9a37ad0cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

