"""initial_migration_fresh_db

Revision ID: 6d4cb587d214
Revises: 
Create Date: 2026-05-22 11:24:46.841783
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4cb587d214'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resend_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_challenges_channel_target', 'otp_challenges', ['channel', 'target'], unique=False)
    op.create_index('ix_otp_challenges_expires_at', 'otp_challenges', ['expires_at'], unique=False)
    op.create_table('phone_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('old_phone', sa.String(length=30), nullable=True),
    sa.Column('new_phone', sa.String(length=30), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_phone_audit_created_at', 'phone_audit_logs', ['created_at'], unique=False)
    op.create_index('ix_phone_audit_user_id', 'phone_audit_logs', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('ix_users_role_created_at', 'users', ['role', 'created_at'], unique=False)
    op.create_table('shops',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address_line', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('pincode', sa.String(length=12), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('opening_hours', sa.String(length=120), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('loyalty_discount_per_point', sa.Float(), server_default=sa.text('0.1'), nullable=False),
    sa.Column('is_open', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_accepting_orders', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('rating_avg', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('rating_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('ix_shops_city_category', 'shops', ['city', 'category'], unique=False)
    op.create_index('ix_shops_is_active_verified', 'shops', ['is_active', 'is_verified'], unique=False)
    op.create_index('ix_shops_owner_id', 'shops', ['owner_id'], unique=False)
    op.create_table('loyalty_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('shop_id', sa.String(length=36), nullable=False),
    sa.Column('points_balance', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tier', sa.String(length=20), server_default=sa.text("'bronze'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'shop_id', name='uq_loyalty_accounts_customer_shop')
    )
    op.create_index('ix_loyalty_accounts_customer_shop', 'loyalty_accounts', ['customer_id', 'shop_id'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shop_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('dietary_type', sa.String(length=20), nullable=False),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_available', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'name', name='uq_menu_items_shop_name')
    )
    op.create_index('ix_menu_items_shop_available', 'menu_items', ['shop_id', 'is_available'], unique=False)
    op.create_index('ix_menu_items_shop_id', 'menu_items', ['shop_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('shop_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('payment_status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('loyalty_points_used', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('loyalty_discount_amount', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('loyalty_points_earned', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('redeem_loyalty_points', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_customer_id_created_at', 'orders', ['customer_id', 'created_at'], unique=False)
    op.create_index('ix_orders_payment_status_created_at', 'orders', ['payment_status', 'created_at'], unique=False)
    op.create_index('ix_orders_shop_id_status', 'orders', ['shop_id', 'status'], unique=False)
    op.create_table('loyalty_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['loyalty_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_loyalty_transactions_account_id_created_at', 'loyalty_transactions', ['account_id', 'created_at'], unique=False)
    op.create_table('menu_item_variants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'name', name='uq_menu_item_variants_item_name')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=30), server_default=sa.text("'razorpay'"), nullable=False),
    sa.Column('provider_order_id', sa.String(length=120), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'created'"), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_order_id', 'payments', ['order_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('shop_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'customer_id', name='uq_reviews_order_customer')
    )
    op.create_index('ix_reviews_shop_id_created_at', 'reviews', ['shop_id', 'created_at'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('variant_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('item_name_snapshot', sa.String(length=140), nullable=False),
    sa.Column('variant_name_snapshot', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['menu_item_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_reviews_shop_id_created_at', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_payments_order_id', table_name='payments')
    op.drop_table('payments')
    op.drop_table('menu_item_variants')
    op.drop_index('ix_loyalty_transactions_account_id_created_at', table_name='loyalty_transactions')
    op.drop_table('loyalty_transactions')
    op.drop_index('ix_orders_shop_id_status', table_name='orders')
    op.drop_index('ix_orders_payment_status_created_at', table_name='orders')
    op.drop_index('ix_orders_customer_id_created_at', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_menu_items_shop_id', table_name='menu_items')
    op.drop_index('ix_menu_items_shop_available', table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index('ix_loyalty_accounts_customer_shop', table_name='loyalty_accounts')
    op.drop_table('loyalty_accounts')
    op.drop_index('ix_shops_owner_id', table_name='shops')
    op.drop_index('ix_shops_is_active_verified', table_name='shops')
    op.drop_index('ix_shops_city_category', table_name='shops')
    op.drop_table('shops')
    op.drop_index('ix_users_role_created_at', table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_phone_audit_user_id', table_name='phone_audit_logs')
    op.drop_index('ix_phone_audit_created_at', table_name='phone_audit_logs')
    op.drop_table('phone_audit_logs')
    op.drop_index('ix_otp_challenges_expires_at', table_name='otp_challenges')
    op.drop_index('ix_otp_challenges_channel_target', table_name='otp_challenges')
    op.drop_table('otp_challenges')
    # ### end Alembic commands ###

