/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopsShopIdRouteImport } from './routes/shops.$shopId'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppLoyaltyRouteImport } from './routes/_app/loyalty'
import { Route as AppOwnerIndexRouteImport } from './routes/_app/owner/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppOrdersOrderIdRouteImport } from './routes/_app/orders.$orderId'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminShopsRouteImport } from './routes/_app/admin/shops'
import { Route as AppAdminOrdersRouteImport } from './routes/_app/admin/orders'
import { Route as AppAdminLoyaltyRouteImport } from './routes/_app/admin/loyalty'
import { Route as AppOwnerShopsNewRouteImport } from './routes/_app/owner/shops.new'
import { Route as AppOwnerShopsShopIdRouteImport } from './routes/_app/owner/shops.$shopId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdRoute = ShopsShopIdRouteImport.update({
  id: '/shops/$shopId',
  path: '/shops/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppLoyaltyRoute = AppLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AppRoute,
} as any)
const AppOwnerIndexRoute = AppOwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersOrderIdRoute = AppOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AppOrdersRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminShopsRoute = AppAdminShopsRouteImport.update({
  id: '/admin/shops',
  path: '/admin/shops',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOrdersRoute = AppAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminLoyaltyRoute = AppAdminLoyaltyRouteImport.update({
  id: '/admin/loyalty',
  path: '/admin/loyalty',
  getParentRoute: () => AppRoute,
} as any)
const AppOwnerShopsNewRoute = AppOwnerShopsNewRouteImport.update({
  id: '/owner/shops/new',
  path: '/owner/shops/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOwnerShopsShopIdRoute = AppOwnerShopsShopIdRouteImport.update({
  id: '/owner/shops/$shopId',
  path: '/owner/shops/$shopId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/loyalty': typeof AppLoyaltyRoute
  '/orders': typeof AppOrdersRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/admin/loyalty': typeof AppAdminLoyaltyRoute
  '/admin/orders': typeof AppAdminOrdersRoute
  '/admin/shops': typeof AppAdminShopsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/admin/': typeof AppAdminIndexRoute
  '/owner/': typeof AppOwnerIndexRoute
  '/owner/shops/$shopId': typeof AppOwnerShopsShopIdRoute
  '/owner/shops/new': typeof AppOwnerShopsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/loyalty': typeof AppLoyaltyRoute
  '/orders': typeof AppOrdersRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/admin/loyalty': typeof AppAdminLoyaltyRoute
  '/admin/orders': typeof AppAdminOrdersRoute
  '/admin/shops': typeof AppAdminShopsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/admin': typeof AppAdminIndexRoute
  '/owner': typeof AppOwnerIndexRoute
  '/owner/shops/$shopId': typeof AppOwnerShopsShopIdRoute
  '/owner/shops/new': typeof AppOwnerShopsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_app/loyalty': typeof AppLoyaltyRoute
  '/_app/orders': typeof AppOrdersRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/_app/admin/loyalty': typeof AppAdminLoyaltyRoute
  '/_app/admin/orders': typeof AppAdminOrdersRoute
  '/_app/admin/shops': typeof AppAdminShopsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/owner/': typeof AppOwnerIndexRoute
  '/_app/owner/shops/$shopId': typeof AppOwnerShopsShopIdRoute
  '/_app/owner/shops/new': typeof AppOwnerShopsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/loyalty'
    | '/orders'
    | '/profile'
    | '/shops/$shopId'
    | '/admin/loyalty'
    | '/admin/orders'
    | '/admin/shops'
    | '/admin/users'
    | '/orders/$orderId'
    | '/admin/'
    | '/owner/'
    | '/owner/shops/$shopId'
    | '/owner/shops/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/loyalty'
    | '/orders'
    | '/profile'
    | '/shops/$shopId'
    | '/admin/loyalty'
    | '/admin/orders'
    | '/admin/shops'
    | '/admin/users'
    | '/orders/$orderId'
    | '/admin'
    | '/owner'
    | '/owner/shops/$shopId'
    | '/owner/shops/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/_app/loyalty'
    | '/_app/orders'
    | '/_app/profile'
    | '/shops/$shopId'
    | '/_app/admin/loyalty'
    | '/_app/admin/orders'
    | '/_app/admin/shops'
    | '/_app/admin/users'
    | '/_app/orders/$orderId'
    | '/_app/admin/'
    | '/_app/owner/'
    | '/_app/owner/shops/$shopId'
    | '/_app/owner/shops/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ShopsShopIdRoute: typeof ShopsShopIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId': {
      id: '/shops/$shopId'
      path: '/shops/$shopId'
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof ShopsShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loyalty': {
      id: '/_app/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof AppLoyaltyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/owner/': {
      id: '/_app/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof AppOwnerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$orderId': {
      id: '/_app/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AppOrdersOrderIdRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/shops': {
      id: '/_app/admin/shops'
      path: '/admin/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AppAdminShopsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/orders': {
      id: '/_app/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AppAdminOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/loyalty': {
      id: '/_app/admin/loyalty'
      path: '/admin/loyalty'
      fullPath: '/admin/loyalty'
      preLoaderRoute: typeof AppAdminLoyaltyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/owner/shops/new': {
      id: '/_app/owner/shops/new'
      path: '/owner/shops/new'
      fullPath: '/owner/shops/new'
      preLoaderRoute: typeof AppOwnerShopsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/owner/shops/$shopId': {
      id: '/_app/owner/shops/$shopId'
      path: '/owner/shops/$shopId'
      fullPath: '/owner/shops/$shopId'
      preLoaderRoute: typeof AppOwnerShopsShopIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppOrdersRouteChildren {
  AppOrdersOrderIdRoute: typeof AppOrdersOrderIdRoute
}

const AppOrdersRouteChildren: AppOrdersRouteChildren = {
  AppOrdersOrderIdRoute: AppOrdersOrderIdRoute,
}

const AppOrdersRouteWithChildren = AppOrdersRoute._addFileChildren(
  AppOrdersRouteChildren,
)

interface AppRouteChildren {
  AppLoyaltyRoute: typeof AppLoyaltyRoute
  AppOrdersRoute: typeof AppOrdersRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppAdminLoyaltyRoute: typeof AppAdminLoyaltyRoute
  AppAdminOrdersRoute: typeof AppAdminOrdersRoute
  AppAdminShopsRoute: typeof AppAdminShopsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppOwnerIndexRoute: typeof AppOwnerIndexRoute
  AppOwnerShopsShopIdRoute: typeof AppOwnerShopsShopIdRoute
  AppOwnerShopsNewRoute: typeof AppOwnerShopsNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLoyaltyRoute: AppLoyaltyRoute,
  AppOrdersRoute: AppOrdersRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppAdminLoyaltyRoute: AppAdminLoyaltyRoute,
  AppAdminOrdersRoute: AppAdminOrdersRoute,
  AppAdminShopsRoute: AppAdminShopsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppOwnerIndexRoute: AppOwnerIndexRoute,
  AppOwnerShopsShopIdRoute: AppOwnerShopsShopIdRoute,
  AppOwnerShopsNewRoute: AppOwnerShopsNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ShopsShopIdRoute: ShopsShopIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
